version: '3'

services:
    mongo:
        image: mongo
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=spotilike
        volumes:
          - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - '27017:27017'
  
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        depends_on:
            - mongo
        ports:
          - "8888:8081"

    spotilike-frontend:
        image: spotilike-frontend
        container_name: spotilike-frontend
        depends_on:
            - mongo
        ports:
          - "8080:8080"

    spotilike-backend:
        image: spotilike-backend
        container_name: spotilike-backend
        restart: always
        depends_on:
            - mongo
        ports:
          - "8889:8889"